config/routes.rb
Rails.application.routes.draw do
  resources :tweets

end

app/models/contain_url.rb
class ContainUrl < ActiveRecord::Base
  belongs_to :tweet
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_many :hashtag_mappings
  has_many :tweets, -> {uniq}, through: :hashtag_mappings
end

app/models/hashtag_mapping.rb
class HashtagMapping < ActiveRecord::Base
  belongs_to :hashtag
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  has_many :hashtag_mappings, -> {uniq}
  has_many :hashtags, -> {uniq}, through: :hashtag_mappings
  has_many :user_mention_mappings, -> {uniq}
  has_many :user_mentions, -> {uniq}, through: :user_mention_mappings

  @client = Twitter::REST::Client.new do |config|
  config.consumer_key = ''
  config.consumer_secret = ''
  config.oauth_token = ''
  config.oauth_token_secret = ''
  end


  def self.grab

    tweets =  @client.user_timeline('barackobama')#, max_id: '375658933253197824')
    Tweet.save_tweets(tweets)
    #tweets = Tweet.last(20)
    while true
      #debugger
      tweets = @client.user_timeline('barackobama', max_id: tweets.last.id.to_s, count: 200)
      Tweet.save_tweets(tweets)
      break if tweets.empty?
    end
  end

  def self.save_tweets(tweets)
    tweets.each do |tweet|
      tw = Tweet.find_or_create_by(origin_id: tweet.id)
      tw.update(
        published_at: tweet.created_at,
        content: tweet.full_text,
        favorite_count: tweet.favorite_count,
        retweet_count: tweet.retweet_count,
        original_url: tweet.url,
        reply: tweet.reply?
      )
      tweet.urls.each do |ul|
        ContainUrl.find_or_create_by(url: ul.attrs[:url], tweet: tw)
      end

      tweet.hashtags.each do |ht|
        hashtag = Hashtag.find_or_create_by(content: ht.attrs[:text])
        tw.hashtags << hashtag
      end

      tweet.user_mentions.each do |um|
        user_mention = UserMention.find_or_create_by(original_id: um.attrs[:id_str])
        user_mention.update(
          screen_name: um.attrs[:screen_name],
          name: um.attrs[:name]
        )
        tw.user_mentions << user_mention
      end
    end
  end
end

app/models/user_mention.rb
class UserMention < ActiveRecord::Base
  has_many :user_mention_mappings
  has_many :tweets, -> {uniq}, through: :user_mention_mappings
end

app/models/user_mention_mapping.rb
class UserMentionMapping < ActiveRecord::Base
  belongs_to :user_mention
  belongs_to :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:published_at, :content, :favorite_count, :retweet_count, :original_url, :reply)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DataSource</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.slim
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      ul
        - @tweet.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :published_at
    = f.datetime_select :published_at
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :favorite_count
    = f.number_field :favorite_count
  .field
    = f.label :retweet_count
    = f.number_field :retweet_count
  .field
    = f.label :original_url
    = f.text_field :original_url
  .field
    = f.label :reply
    = f.check_box :reply
  .actions = f.submit

app/views/tweets/edit.html.slim
h1 Editing tweet

== render 'form'

= link_to 'Show', @tweet
'|
= link_to 'Back', tweets_path

app/views/tweets/index.html.slim
h1 Listing tweets

table
  thead
    tr
      th Published at
      th Content
      th Favorite count
      th Retweet count
      th Original url
      th Reply
      th
      th
      th

  tbody
    - @tweets.each do |tweet|
      tr
        td = tweet.published_at
        td = tweet.content
        td = tweet.favorite_count
        td = tweet.retweet_count
        td = tweet.original_url
        td = tweet.reply
        td = link_to 'Show', tweet
        td = link_to 'Edit', edit_tweet_path(tweet)
        td = link_to 'Destroy', tweet, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Tweet', new_tweet_path

app/views/tweets/new.html.slim
h1 New tweet

== render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.slim
p#notice = notice

p
  strong Published at:
  = @tweet.published_at
p
  strong Content:
  = @tweet.content
p
  strong Favorite count:
  = @tweet.favorite_count
p
  strong Retweet count:
  = @tweet.retweet_count
p
  strong Original url:
  = @tweet.original_url
p
  strong Reply:
  = @tweet.reply

= link_to 'Edit', edit_tweet_path(@tweet)
'|
= link_to 'Back', tweets_path